server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: assembleia-cooperativa
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://34.95.144.95:3306/DBAssembleia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'XjY2SV,-KbR@vPO:'